name: Quality Assurance
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  format-typecheck-test:
    name: Formatting, types and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node & NPM
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install lib dependencies
        run: npm ci

      - name: Formatting
        run: npm run format:check

      - name: Type check
        run: npm run typecheck

      - name: Linting
        run: npm run lint

      - name: Run tests
        run: npm test
